---
  - name: Install UFW
    apt:
      name:
        - ufw
      state: latest
      update_cache: yes
  
  - name: Enable UFW logging
    ufw:
      logging: 'on'

  - name: Allow all access to specific tcp ports
    ufw:
      rule: allow
      port: '{{ item }}'
      proto: tcp
    loop:
      - '22'
      - '80'
    notify:
      - reload ufw

  - name: Reject connections instead of Deny
    ufw:
      rule: reject
      port: auth
      log: yes
    notify:
      - reload ufw

  - name: Rate limit SSH connection
    ufw:
      rule: limit
      port: ssh
      proto: tcp
    notify:
      - reload ufw

  - name: Allow all access from RFC1918 networks to this host
    ufw:
      rule: allow
      src: '{{ item }}'
    loop:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    notify:
      - reload ufw

  - name: Change UFW state to Enabled
    ufw:
      state: enabled

  handlers:
  - name: reload ufw
    ufw:
      state: reloaded