---
- name: Push config to cluster
  hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Check that required packages are installed"
      ansible.builtin.apt:
        name:
          - curl
          - file
          - git
          - htop
          - tree
          - firewalld
          - sshpass
        state: latest
        update_cache: yes
      when: default_packages

    - name: Update cache and upgrade all packages
      register: update_sys
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      when: upgrade_cluster

    - name: Display the last line of the previous task to check the stats
      debug:
        msg:  "{{update_sys.stdout_lines|last}}"
      when: upgrade_cluster

    - name: Add mappings to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
            192.168.0.200 underworld
            192.168.0.201 hades
            192.168.0.202 persephone
            192.168.0.203 nyx
            192.168.0.204 charon
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      when: insert_hosts
