- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
        {% for item in ansible_play_batch %}
        {{ hostvars[item].ansible_ssh_host }}   {{ item }}    
        {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"