---
- name: Update cache and upgrade all packages
  register: updatesys
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Display the last line of the previous task to check the stats
  debug:
    msg:  "{{updatesys.stdout_lines|last}}"